### ISSUE TITLE
Backspace key is sent to Vim --- why?

### ISSUE THREAD

**Issue by lervag** [sunaku/tmux-navigate#1]
I just tested this as an alternative to vim-tmux-navigator. I like the idea, but I experienced a strange bug. I've localized it to the following line of code:

https://github.com/sunaku/tmux-navigate/blob/73536d8a9ce9f6b5998b71b2ab988d5bac73805f/tmux-navigate.tmux#L61

I don' understand why this is there. For most people, it won't do much (except move one character back), but I've mapped backspace to `<c-o>`, and so this line made things behave weirdly when navigating out of a Vim pane.

**Comment by lervag** [comment]
> Wrapping focus around on window edges is tmux's native behavior. Try creating two side-by-side tmux panes and then run tmux select-pane -R in the right-hand pane: you'll land on the left-hand pane.
>
> Could you try installing the Vim plugin included in this repo? I think that may fix this issue and also #1.

I don't understand why you think installing the Vim plugin would have an effect on the issue I've raised here. As mentioned, the line I've indicated sends a backspace key to the Vim window, and if I remove the line, things work as expected. Am I misunderstanding something? Perhaps you could explain why this line is there?

**Comment by sunaku** [comment]
That line was added in commit 7d45311e478bcb86f26dec38aff8c1befd88d2c0, which is described as:
> tmux: erase stray ESC + hjkl for misidentified Vim

Sometimes I need to use vanilla Vim on machines that are newly imaged (not yet configured with my vimrc) or are very old (they run an ancient version of Vim that has no hope of supporting my vimrc).  In such cases, I find that Vim changes the pane title to "Thanks for flying Vim" and doesn't clean up after itself: the title remains behind as the pane title _even after_ I quit Vim.  This used to cause an older version of this plugin to wrongly identify the pane as still running Vim. :thinking:  I need to check if this still applies.

Another use case was performance testing: I would split a few tmux panes and hold down the navigation shortcut keys.  After some tens of cycles, the shortcut keys would intermittently be deposited into some of the panes, as a result of the race condition caused by sleeping for `@navigate-timeout` seconds.

> I don't understand why you think installing the Vim plugin would have an effect on the issue I've raised here. As mentioned, the line I've indicated sends a backspace key to the Vim window, and if I remove the line, things work as expected. Am I misunderstanding something? Perhaps you could explain why this line is there?

If you didn't install the Vim plugin, the pane title wouldn't change when you navigated inside Vim.  Therefore, we would fall into the case of the pane being misidentified as running Vim when it wasn't.

**Comment by lervag** [comment]
Ok, thanks for the explanation. I still think sending the backspace key is wrong, though. :)

**Comment by sunaku** [comment]
Fixed now in commit c93c99a09f422386060e044eb20365019d0ae82b.  Thanks for reporting this issue.
